#ifndef PHYSICS_CONSTANTS_GLSL
#define PHYSICS_CONSTANTS_GLSL

#define PLAYER_GRAVITY 32.0f
#define PLAYER_TERMINAL_VELOCITY 55.0f
#define PLAYER_MAX_GROUND_SPEED 6.5f
#define PLAYER_GROUND_ACCELERATION 32.0f
#define PLAYER_AIR_ACCELERATION 12.0f
#define PLAYER_GROUND_DAMPING 14.0f
#define PLAYER_AIR_DAMPING 0.5f
#define PLAYER_JUMP_SPEED 16.0f
#define PLAYER_SURFACE_NORMAL_EPSILON 0.02f
#define PLAYER_MAX_SLOPE_DOT 0.6f
#define PLAYER_SPRINT_MULTIPLIER 2.0f

#endif
