#ifndef SCENE_CONSTANTS_GLSL
#define SCENE_CONSTANTS_GLSL

const float SCENE_MAX_DISTANCE = 512.0;
const int SCENE_MAX_STEPS = 512;

const float SCENE_SHADOW_EPSILON = 0.001;
const int SCENE_MAX_SHADOW_STEPS = 64;

const float SCENE_FADE_START_FACTOR = 0.5;
const float SCENE_FADE_END_FACTOR = 1.0;

const float SCENE_NOISE_MAX_DISTANCE = 15.0;
const float SCENE_NOISE_MAX_STRENGTH = 0.05;
const float SCENE_NOISE_SHADOW_MIN_BLEND = 0.1;
const float SCENE_NOISE_SHADOW_MAX_BLEND = 1.0;
const float SCENE_NOISE_SCALE = 10.0;

const float SCENE_NEAR_LIGHT_DISTANCE = 16.0;
const float SCENE_NEAR_LIGHT_STRENGTH = 0.15;
const float SCENE_NEAR_LIGHT_POWER = 1.3;

const float SCENE_WHITE_SURFACE_LUMINANCE = 1.0;
const float SCENE_WHITE_SURFACE_DEPTH_MAX = 20.0;
const float SCENE_WHITE_SURFACE_DEPTH_REDUCE = 0.15;

const float SCENE_SHADOW_MIN_HARD = 0.1;
const float SCENE_SHADOW_SOFT_BLEND = 0.6;
const float SCENE_SHADOW_SOFT_POWER = 0.3;

const float SCENE_FOV_ASPECT_CORRECTION = 1.0;
const float SCENE_DEPTH_VALID_MIN = 0.0;

const float SCENE_NORMAL_UNPACK_SCALE = 2.0;
const float SCENE_NORMAL_UNPACK_BIAS = 1.0;
const float SCENE_HIT_FLAG_THRESHOLD = 0.5;

const vec3 SCENE_LUMINANCE_WEIGHTS = vec3 (0.299, 0.587, 0.114);
const float SCENE_SRGB_GAMMA = 1.0 / 3.2;

#endif
